### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by Lucky390163** [TJYSunset/Phocid#8] opened 2024-12-02 05:44 UTC
Almost become a perfect app, but can you look at the clip that how the app is lagging? Too much on scrolling.
Just installed the latest version 1min ago.

**Comment by TJYSunset** [comment] 2024-12-02 05:48
Yes I know that. Mostly a Google issue, blame them for their **** framework. The current version is the best compromise I can make.

**Comment by Lucky390163** [comment] 2024-12-02 05:49
I you have problems in maintenance you can use fossify music source code.It superbly optimized in scrolling

**Comment by TJYSunset** [comment] 2024-12-02 05:51
They are not using Jetpack Compose as their UI framework, instead they are View-based.

**Comment by Lucky390163** [comment] 2024-12-02 05:53
Or Auxio that's much i have - https://github.com/OxygenCobalt/Auxio.git

**Comment by Lucky390163** [comment] 2024-12-02 05:56
Maybe the developers can help you maintain the app.Only that much i can say

**Comment by TJYSunset** [comment] 2024-12-02 05:57
These are all View-based, the supposedly "legacy" technology. Technically I could use View components inside Compose, but I'd have to revert all the changes some day when Google decides to `@Deprecate`™ such possibility.

The best bet is to wait for Google to fix their performance problems.

**Comment by Lucky390163** [comment] 2024-12-02 05:58
And one more small request please add recently added songs tab like this app called musicolet
![Screenshot_20241202_112801_Musicolet](https://github.com/user-attachments/assets/44b3b023-f004-41f9-9441-408217c1d71e)

**Comment by Lucky390163** [comment] 2024-12-02 05:59
That will give this app a new functionality

**Comment by TJYSunset** [comment] 2024-12-03 14:49
Fixed in 9a4bb292c8896a8f09c3bb7f7ef0594902a478ee

Have a build with fixes applied here (Can't publish a new version because I had to use date as version number)
[https://github.com/user-attachments/files/17994718/app-release.zi](https://github.com/user-attachments/files/17994718/app-release.zip)

**Comment by CaffeineOnIce** [comment] 2024-12-03 15:20
On the latest build that you fixed, sorry to say, lag is still there. But yeah, it's very usable than before.

[Link to the video.](https://gofile.io/d/wzkp7s)

**Comment by TJYSunset** [comment] 2024-12-03 15:27
Can't replicate that even in a playlist with 5000 items. Did you ran out of RAM, or by any chance your files are on an external SD card or something?

**Comment by CaffeineOnIce** [comment] 2024-12-03 15:31
Nope. All in internal memory. Running on Samsung One UI 6.1, Android 14, Samsung S24, on Exynos, btw.

**Comment by TJYSunset** [comment] 2024-12-03 15:43
Can you test this build that replaces all images with placeholders? I suspect the new lag is caused by image loading.
[app-release.zip](https://github.com/user-attachments/files/17995478/app-release.zip)

**Comment by CaffeineOnIce** [comment] 2024-12-03 16:22
Can confirm. It do be the image loading that's causing the mess. It's fluid in this build. artwork loading causes the lag.

**Comment by TJYSunset** [comment] 2024-12-03 16:41
Does this build lag? Maybe it's because the cache saturated, and I can't replicate because my 5000-item list only consists of 1000 tracks duplicated 5 times (so only 1000 images are actually loaded). I removed the caching mechanism entirely.

Ironically caching was originally meant for better performance.

[app-release.zip](https://github.com/user-attachments/files/17996187/app-release.zip)

**Comment by CaffeineOnIce** [comment] 2024-12-03 17:17
oh yeah, it's close to perfection. Just saw a tiny lag, but it's nothing it be worried about. It's great.

**Comment by TJYSunset** [comment] 2024-12-03 17:24
Committed as 36bdd1024deb9c35f170f3631028e201e945021e

**Comment by CaffeineOnIce** [comment] 2024-12-04 06:57
Nope. Lag is back again. For the last 22 mins ago build. It's weird. Same lag. scrolling.

**Comment by TJYSunset** [comment] 2024-12-04 07:05
Can you make sure the version number in about section "v20241204"? Technically this is impossible, since no related changes have been made after that.

**Comment by CaffeineOnIce** [comment] 2024-12-04 07:57
Nevermind, I just uninstalled it again and reinstalled it. It's now fine. must have been a fluke.

**Closed** 2024-12-04 08:30 UTC
